#This docker file run a layer over gprasad09/sparkbase_user image to make config for manager node
FROM gprasad09/spark_withuser1:latest
#RUN pip install jupyter && pip install pandas && pip install pyarrow && pip install findspark
CMD service ssh start && bash